import os, json, requests
from datetime import datetime, timedelta
from urllib.request import urlopen, Request
import xml.etree.ElementTree as ET
import streamlit as st

SAMBANOVA_KEY   = "cf4f3348-46b8-4b52-aa62-e9febd509c98"
SAMBANOVA_URL   = "https://api.sambanova.ai/v1/chat/completions"
MODEL           = "Qwen3-235B"
TRADE_PROB_MIN  = 0.60
BASE_DIR        = os.path.dirname(os.path.abspath(__file__))
MEMORY_DIR      = os.path.join(BASE_DIR, "memory")
WORLD_VIEW_F    = os.path.join(MEMORY_DIR, "WORLD_VIEW.md")
SIGNAL_LOG_F    = os.path.join(MEMORY_DIR, "signal_log.json")
BRIEFING_CACHE  = os.path.join(MEMORY_DIR, "briefing_cache.json")
SCENARIO_CACHE  = os.path.join(MEMORY_DIR, "scenario_cache.json")

NEWS_FEEDS = {
    "XAU/USD": "https://feeds.finance.yahoo.com/rss/2.0/headline?s=GC%3DF&region=US&lang=en-US",
    "S&P 500": "https://feeds.finance.yahoo.com/rss/2.0/headline?s=%5EGSPC&region=US&lang=en-US",
    "Oil":     "https://feeds.finance.yahoo.com/rss/2.0/headline?s=CL%3DF&region=US&lang=en-US",
    "Nasdaq":  "https://feeds.finance.yahoo.com/rss/2.0/headline?s=%5EIXIC&region=US&lang=en-US",
    "Bitcoin": "https://feeds.finance.yahoo.com/rss/2.0/headline?s=BTC-USD&region=US&lang=en-US",
    "Silver":  "https://feeds.finance.yahoo.com/rss/2.0/headline?s=SI%3DF&region=US&lang=en-US",
}

# ─────────────────────────────────────────────
# SYSTEM PROMPTS
# ─────────────────────────────────────────────

BRIEFING_SYSTEM = """## ROLE
You are a quantitative gold trading analyst combining macroeconomic regime analysis, Smart Money Concepts (SMC) technical structure, and ML signal interpretation. You operate inside a live trading pipeline where signals are generated by a two-stage model: a LightGBM regressor predicting next-day XAU/USD log returns, calibrated by a logistic regression model outputting P(direction correct) given the current market regime.

## TASK
Analyse today's XAU/USD signal pipeline output. Produce a structured briefing that: (1) establishes the current macro regime and whether it supports the ML signal, (2) explains what the LightGBM features are saying in plain English, (3) maps SMC levels to the signal direction, (4) connects correlated assets to gold, (5) gives a forward outlook grounded in structure and macro, (6) updates your persistent world view in token-efficient format.

## CONTEXT — PIPELINE ARCHITECTURE
LightGBM trained on 20 years daily gold data, 15 features:
- Close_Returns, Log_Returns: daily price movement
- EURUSD_Returns, USDJPY_Returns: dollar strength correlations — when USD weakens gold rises
- BB_PctB: position in 20-day Bollinger Band (0=lower band, 1=upper band, >1=overbought)
- Price_Over_EMA50, Price_Over_EMA200: how far price is from its trend anchors
- Bull_Trend: (EMA50-EMA200)/EMA200 — positive=bull regime, negative=bear regime
- MACD_Signal_Norm: momentum signal normalised by price level
- LogReturn_ZScore, Return_ZScore: how extreme today's move is vs 20-day history
- Return_Percentile, Volume_Percentile: rank vs last 100 days
- Pct_From_AllTimeHigh: drawdown from ATH — context for value
- Macro_Fast: 8-component z-score of FRED rates (DFII10, DFII5, DGS2, FEDFUNDS + 1-day deltas). Positive=tight monetary policy=bearish for gold. Negative=easy monetary policy=bullish for gold. This is the single most important macro feature.
Calibrator inputs: LightGBM prediction + Bull_Trend + Macro_Fast + BB_PctB + EMA200 ratio. Signal gate: prob>=0.45 AND |pred_z|>=0.6. Trade activation: prob>=0.60 only.
SMC from 4H candles: BOS (break of structure — continuation), CHoCH (change of character — reversal), Order Blocks (last opposing candle before the break — institutional demand/supply zone), S/R clusters (swing points with 2+ touches — proven reaction zones).
The model runs at night Morocco time (evening before market opens next session). The daily candle closes at 1:30pm NY. We always use the confirmed closed candle.

## REASONING APPROACH
Step 1: Read Macro_Fast — establishes the monetary regime. Step 2: Check Bull_Trend — confirms technical trend. Step 3: Read pred_z — how unusual is today's model conviction vs its own history. Step 4: Check BB_PctB — entry quality context (>0.8 = overbought caution on BUY). Step 5: Map nearest SMC levels to signal direction — alignment = quality. Step 6: Synthesise.

## STOP CONDITIONS
Do not conclude until you have addressed: macro regime, ML feature extremes, SMC alignment, correlated asset positioning, and at least one forward risk or catalyst.

## OUTPUT
Respond ONLY with valid JSON. No markdown, no backticks, no preamble."""


SCENARIO_SYSTEM = """## ROLE
You are a senior gold trader and quantitative analyst preparing a complete trade brief. You have access to a full ML pipeline output, SMC structural analysis, macro data, and live market intelligence. Your job is to synthesise all of this into a single actionable trade scenario that a human trader can execute with full understanding of the reasoning behind every level.

## THE PIPELINE — FULL JOURNEY
This pipeline was built from scratch and trained on 20 years of XAU/USD daily data. Here is the complete story:

STAGE 1 — LightGBM Regressor
A gradient boosting model trained to predict the next-day log return of XAU/USD. It uses 15 engineered features capturing: daily price momentum (Close_Returns, Log_Returns), currency correlations (EURUSD_Returns, USDJPY_Returns), trend structure (Bull_Trend = (EMA50-EMA200)/EMA200, Price_Over_EMA50, Price_Over_EMA200), momentum (MACD_Signal_Norm), volatility context (BB_PctB = Bollinger Band position), statistical extremity (LogReturn_ZScore, Return_ZScore, Return_Percentile, Volume_Percentile), drawdown context (Pct_From_AllTimeHigh), and the most important single feature: Macro_Fast — an 8-component z-score of FRED interest rate data (10yr and 5yr real yields DFII10/DFII5, 2yr nominal DGS2, fed funds rate FEDFUNDS, plus their 1-day deltas). When Macro_Fast is positive, monetary conditions are tightening — historically bearish for gold. When negative, conditions are easing — historically bullish for gold. The model outputs a raw prediction value (the predicted log return).

STAGE 2 — Logistic Calibrator
The raw prediction plus four regime-sensitive features (Bull_Trend, Macro_Fast, BB_PctB, EMA200 ratio) are passed to a logistic regression calibrator that outputs P(direction correct) — the probability that the LightGBM direction call is right given the current market regime. This is not a random probability. It is a regime-adjusted confidence score.

SIGNAL GATE
A signal only fires when BOTH conditions are met: calibrated probability >= 0.45 AND |pred_z| >= 0.6 (pred_z = how many standard deviations the prediction is from the model's own historical mean — measures conviction). Trade scenario generation requires prob >= 0.60.

SMC STRUCTURE (4H candles, 58-day window)
BOS (Break of Structure): price broke above a swing high (bullish BOS = continuation of uptrend) or below a swing low (bearish BOS = continuation of downtrend). This tells you institutional flow is committed.
CHoCH (Change of Character): price broke against the previous swing — a reversal signal. A bullish CHoCH after a downtrend is the first sign of a new uptrend beginning.
Order Blocks: the last opposing candle before a BOS or CHoCH. This is where institutions placed their orders. Price often returns to these zones before continuing.
S/R Clusters: price levels touched by swing highs/lows 2+ times. These are proven reaction zones.

CANDLE AND TIMING CONTEXT
Daily candle closes at 1:30pm NY (6:30pm Morocco). The pipeline runs at ~9pm Morocco — after FRED data publishes and before next session opens. We always trade the next session based on today's confirmed closed candle. This is a daily timeframe signal used to identify next-day directional bias.

ATR-BASED RISK MANAGEMENT
Stop loss and take profit are computed using 14-day ATR (Average True Range) which measures true daily volatility. SL = 1.5x ATR from entry (gives the trade room to breathe without being too wide). TP = 2.5x ATR from entry (minimum 1.67 R:R ratio). These are adjusted for the current volatility regime — in high volatility the levels are wider, in low volatility they are tighter.

## YOUR TASK
Using ALL the data provided — pipeline output, SMC levels, ATR, macro regime, current price, web search results, headlines — produce a complete trade scenario. Think like a trader who has studied this setup, not like an algorithm outputting numbers.

## REASONING STEPS YOU MUST FOLLOW
1. Confirm the signal direction and why the model fired — which features pushed it?
2. Identify the best entry zone — which SMC level (OB or S/R) is nearest on the signal side?
3. Set SL using 1.5x ATR below entry (BUY) or above entry (SELL)
4. Set TP using 2.5x ATR from entry, adjusted to nearest structural target
5. Assess conviction: HIGH (prob>0.70, SMC aligned, macro aligned), MEDIUM (prob 0.60-0.70 or partial alignment), LOW (borderline — flag it)
6. Write the scenario in plain English as if briefing a trader before market open
7. Include specific price management instructions — what to do if price does X or Y

## OUTPUT
Respond ONLY with valid JSON. No markdown, no backticks, no preamble."""


# ─────────────────────────────────────────────
# MEMORY
# ─────────────────────────────────────────────

def _ensure_memory():
    os.makedirs(MEMORY_DIR, exist_ok=True)

def _today_file():
    return os.path.join(MEMORY_DIR, f"{datetime.now().strftime('%Y-%m-%d')}.md")

def _read_world_view():
    _ensure_memory()
    return open(WORLD_VIEW_F).read().strip() if os.path.exists(WORLD_VIEW_F) else ""

def _write_world_view(content):
    _ensure_memory()
    with open(WORLD_VIEW_F, "w") as f:
        f.write(content)

def _append_daily(content):
    _ensure_memory()
    with open(_today_file(), "a") as f:
        f.write(content + "\n")

def _read_recent_daily(days=3):
    _ensure_memory()
    result = ""
    for i in range(days):
        d    = (datetime.now() - timedelta(days=i)).strftime("%Y-%m-%d")
        path = os.path.join(MEMORY_DIR, f"{d}.md")
        if os.path.exists(path):
            c = open(path).read().strip()
            if c:
                result += f"[{d}]\n{c}\n"
    return result.strip()

def _load_signal_log():
    _ensure_memory()
    if os.path.exists(SIGNAL_LOG_F):
        try:
            return json.load(open(SIGNAL_LOG_F))
        except Exception:
            pass
    return []

def _save_signal_log(log):
    with open(SIGNAL_LOG_F, "w") as f:
        json.dump(log[-60:], f, indent=2)


# ─────────────────────────────────────────────
# BRIEFING CACHE
# ─────────────────────────────────────────────

def _load_briefing_cache(date_str):
    _ensure_memory()
    if not os.path.exists(BRIEFING_CACHE):
        return None
    try:
        data = json.load(open(BRIEFING_CACHE))
        if data.get("date") == date_str:
            return data.get("result")
    except Exception:
        pass
    return None

def _save_briefing_cache(date_str, result):
    _ensure_memory()
    with open(BRIEFING_CACHE, "w") as f:
        json.dump({"date": date_str, "result": result}, f)


# ─────────────────────────────────────────────
# SCENARIO CACHE
# ─────────────────────────────────────────────

def _load_scenario_cache(date_str):
    _ensure_memory()
    if not os.path.exists(SCENARIO_CACHE):
        return None
    try:
        data = json.load(open(SCENARIO_CACHE))
        if data.get("date") == date_str:
            return data.get("result")
    except Exception:
        pass
    return None

def _save_scenario_cache(date_str, result):
    _ensure_memory()
    with open(SCENARIO_CACHE, "w") as f:
        json.dump({"date": date_str, "result": result}, f)


# ─────────────────────────────────────────────
# WEB + HEADLINES
# ─────────────────────────────────────────────

def _ddg_search(query, max_results=4):
    try:
        url = f"https://api.duckduckgo.com/?q={requests.utils.quote(query)}&format=json&no_html=1&skip_disambig=1"
        r   = requests.get(url, timeout=8, headers={"User-Agent": "Mozilla/5.0"})
        data = r.json()
        out  = []
        if data.get("AbstractText"):
            out.append(data["AbstractText"][:300])
        for t in data.get("RelatedTopics", [])[:max_results]:
            if isinstance(t, dict) and t.get("Text"):
                out.append(t["Text"][:200])
        return out
    except Exception:
        return []

def _fetch_headlines(url, max_items=4):
    try:
        req = Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urlopen(req, timeout=6) as resp:
            raw = resp.read()
        root    = ET.fromstring(raw)
        channel = root.find("channel")
        if channel is None:
            return []
        items  = []
        cutoff = datetime.utcnow() - timedelta(days=5)
        for item in channel.findall("item")[:max_items * 2]:
            title   = (item.findtext("title") or "").strip()
            pub_raw = (item.findtext("pubDate") or "").strip()
            if not title:
                continue
            try:
                pub_dt = datetime.strptime(pub_raw, "%a, %d %b %Y %H:%M:%S %z").replace(tzinfo=None)
                if pub_dt < cutoff:
                    continue
            except Exception:
                pass
            items.append(title)
            if len(items) >= max_items:
                break
        return items
    except Exception:
        return []

def fetch_all_headlines():
    return {a: _fetch_headlines(u) for a, u in NEWS_FEEDS.items()}


# ─────────────────────────────────────────────
# QWEN API CALL
# ─────────────────────────────────────────────

def _call_qwen(messages, max_tokens=1400):
    try:
        r = requests.post(
            SAMBANOVA_URL,
            headers={"Authorization": f"Bearer {SAMBANOVA_KEY}", "Content-Type": "application/json"},
            json={"model": MODEL, "messages": messages, "max_tokens": max_tokens, "temperature": 0.3},
            timeout=90,
        )
        raw = r.json()["choices"][0]["message"]["content"].strip()
        raw = raw.replace("```json", "").replace("```", "").strip()
        if "<think>" in raw:
            end = raw.find("</think>")
            if end != -1:
                raw = raw[end + 8:].strip()
        return raw
    except Exception as e:
        return json.dumps({"error": str(e)})


# ─────────────────────────────────────────────
# BRIEFING
# ─────────────────────────────────────────────

def _briefing_user_msg(signal_data, smc_data, headlines, web_block=""):
    sig    = signal_data.get("signal", "NO SIGNAL")
    prob   = signal_data.get("prob", 0)
    pred_z = signal_data.get("pred_z", 0)
    bt     = signal_data.get("bull_trend", 0)
    mf     = signal_data.get("macro_fast", 0)
    bb     = signal_data.get("bb_pctb", 0)
    ema200 = signal_data.get("ema200", 1)
    close  = signal_data.get("close", 0)
    w_high = signal_data.get("weekly_high", 0)
    w_low  = signal_data.get("weekly_low", 0)
    i_high = signal_data.get("intraday_high")
    i_low  = signal_data.get("intraday_low")
    date   = signal_data.get("date", datetime.now().strftime("%Y-%m-%d"))

    bt_lbl = "BULL" if bt > 0.02 else "BEAR" if bt < -0.02 else "NEUTRAL"
    mf_lbl = "TIGHT" if mf > 0.5 else "EASY" if mf < -0.5 else "NEUTRAL"

    res = sorted([l for l in smc_data if l["price"] > close], key=lambda x: x["price"])
    sup = sorted([l for l in smc_data if l["price"] < close], key=lambda x: x["price"], reverse=True)

    news = ""
    for asset, titles in headlines.items():
        if titles:
            news += f"\n{asset}: " + " | ".join(titles[:3])

    world_view  = _read_world_view()
    recent_days = _read_recent_daily(3)
    log         = _load_signal_log()[-10:]
    log_block   = ""
    if log:
        log_block = "\nSignal history:\n" + "".join(
            f"  {e['date']} {e['signal']} p={e['prob']:.2f} {e.get('outcome','pending')}\n"
            for e in log)

    return f"""DATE: {date}
MARKET: ${close:,.2f} | {sig} | prob={prob:.4f} | pred_z={pred_z:+.4f}
Bull_Trend={bt:+.4f}[{bt_lbl}] | Macro_Fast={mf:+.4f}[{mf_lbl}] | BB_PctB={bb:.4f} | EMA200={ema200:.4f}
Weekly: ${w_low:,.1f}–${w_high:,.1f}{f' | Intraday: ${i_low:,.1f}–${i_high:,.1f}' if i_high else ''}
SMC Resistance: {' | '.join(f"${l['price']:,.1f} {l['type']}" for l in res[:5]) or 'none'}
SMC Support:    {' | '.join(f"${l['price']:,.1f} {l['type']}" for l in sup[:5]) or 'none'}
Headlines:{news or ' none'}
{f'Web:{chr(10)}{web_block}' if web_block else ''}
{'World view:' + chr(10) + world_view if world_view else ''}
{'Recent sessions:' + chr(10) + recent_days if recent_days else ''}
{log_block}
Return ONLY valid JSON:
{{
  "market_context": "2-3 sentences on global macro and what it means for gold today.",
  "feature_reading": "2-3 sentences explaining Bull_Trend, Macro_Fast, BB_PctB, pred_z in plain English.",
  "smc_analysis": "2-3 sentences on how SMC structure aligns or conflicts with the signal.",
  "asset_connections": "2 sentences on S&P, Oil, Nasdaq, Bitcoin, Silver relative to gold.",
  "forward_outlook": "2 sentences on catalysts, key levels, risks to watch.",
  "world_view_update": "Token-efficient. Headers: ## Macro Regime | ## Gold Structure | ## Central Banks | ## Patterns. Max 350 words. Update only what changed materially.",
  "run_note": "One line for daily log."
}}"""


def run_briefing(signal_data, smc_levels, status_callback=None):
    date_str = signal_data.get("date", datetime.now().strftime("%Y-%m-%d"))

    cached = _load_briefing_cache(date_str)
    if cached:
        if status_callback:
            status_callback("Loaded from today's cache — no API call needed")
        return cached, {}

    if status_callback:
        status_callback("Fetching headlines...")
    headlines = fetch_all_headlines()

    if status_callback:
        status_callback("Searching web...")
    snips     = _ddg_search(f"gold XAU outlook {date_str}")
    web_block = "\n".join(f"- {s}" for s in snips) if snips else ""

    if status_callback:
        status_callback("Calling Qwen3-235B...")

    user_msg = _briefing_user_msg(signal_data, smc_levels, headlines, web_block)
    messages = [
        {"role": "system", "content": BRIEFING_SYSTEM},
        {"role": "user",   "content": user_msg},
    ]
    raw = _call_qwen(messages, max_tokens=1400)

    try:
        result = json.loads(raw)
    except Exception:
        result = {"error": "JSON parse failed", "raw": raw[:300]}

    if "error" not in result:
        wv = result.get("world_view_update", "")
        if wv:
            _write_world_view(wv)
        _append_daily(
            f"\n### {datetime.now().strftime('%H:%M')}\n"
            f"Signal={signal_data.get('signal')} prob={signal_data.get('prob',0):.3f} "
            f"close=${signal_data.get('close',0):,.2f}\n"
            f"{result.get('run_note','')}\n"
        )
        log = _load_signal_log()
        log.append({
            "date":    date_str,
            "signal":  signal_data.get("signal", "NO SIGNAL"),
            "prob":    round(signal_data.get("prob", 0), 4),
            "outcome": "pending",
            "note":    result.get("run_note", ""),
        })
        _save_signal_log(log)
        _save_briefing_cache(date_str, result)

    return result, headlines


# ─────────────────────────────────────────────
# SCENARIO BUILDER
# ─────────────────────────────────────────────

def _compute_atr(feat_df):
    try:
        import yfinance as yf
        from datetime import datetime, timedelta
        raw = yf.download("GC=F",
                          start=datetime.today()-timedelta(days=30),
                          end=datetime.today(),
                          auto_adjust=False, progress=False)
        if isinstance(raw.columns, __import__("pandas").MultiIndex):
            raw.columns = raw.columns.get_level_values(0)
        if raw.empty or len(raw) < 5:
            raise ValueError("empty")
        high  = raw["High"].values
        low   = raw["Low"].values
        close = raw["Close"].values
        tr    = []
        for i in range(1, len(high)):
            tr.append(max(high[i]-low[i],
                          abs(high[i]-close[i-1]),
                          abs(low[i]-close[i-1])))
        return round(sum(tr[-14:])/min(14, len(tr)), 2)
    except Exception:
        if feat_df is not None and "Close_Returns" in feat_df.columns:
            avg_ret = abs(feat_df["Close_Returns"].tail(14)).mean()
            close   = float(feat_df["Close_XAUUSD"].iloc[-1])
            return round(avg_ret * close, 2)
        return 30.0


def _fetch_live_open():
    """Fetch today's opening candle price to compare against yesterday's levels."""
    try:
        import yfinance as yf
        from datetime import datetime, timedelta
        now   = datetime.utcnow()
        start = now.replace(hour=0, minute=0, second=0, microsecond=0)
        if start >= now:
            start = start - timedelta(days=1)
        raw = yf.download("GC=F", start=start, end=now,
                          interval="1h", auto_adjust=False, progress=False)
        if isinstance(raw.columns, __import__("pandas").MultiIndex):
            raw.columns = raw.columns.get_level_values(0)
        if raw.empty:
            return None, None, None
        open_p  = float(raw["Open"].iloc[0])
        current = float(raw["Close"].iloc[-1])
        high    = float(raw["High"].max())
        low     = float(raw["Low"].min())
        return open_p, current, (high, low)
    except Exception:
        return None, None, None


def _yesterday_review(signal_data, smc_data):
    """Compare yesterday's signal and levels to today's opening — give Qwen context on how it did."""
    open_p, live_price, day_range = _fetch_live_open()
    sig   = signal_data.get("signal", "NO SIGNAL")
    close = signal_data.get("close", 0)

    lines = []
    if open_p:
        gap = open_p - close
        lines.append(f"Yesterday close: ${close:,.2f} | Today open: ${open_p:,.2f} | Gap: {gap:+.1f}")
    if live_price:
        lines.append(f"Current live price: ${live_price:,.2f}")
    if day_range:
        lines.append(f"Today's range so far: ${day_range[1]:,.1f} – ${day_range[0]:,.1f}")

    if open_p and sig in ("BUY", "SELL"):
        moved = open_p - close
        if sig == "BUY":
            lines.append(f"Signal was BUY at ${close:,.2f}. Price opened {'higher' if moved > 0 else 'lower'} by ${abs(moved):.1f}.")
            if live_price:
                from_close = live_price - close
                lines.append(f"From signal close to now: {from_close:+.1f} ({'positive — signal working' if from_close > 0 else 'negative — signal under pressure'})")
        else:
            lines.append(f"Signal was SELL at ${close:,.2f}. Price opened {'lower' if moved < 0 else 'higher'} by ${abs(moved):.1f}.")
            if live_price:
                from_close = live_price - close
                lines.append(f"From signal close to now: {from_close:+.1f} ({'negative — signal working' if from_close < 0 else 'positive — signal under pressure'})")

    if open_p and smc_data:
        res = sorted([l for l in smc_data if l["price"] > close], key=lambda x: x["price"])
        sup = sorted([l for l in smc_data if l["price"] < close], key=lambda x: x["price"], reverse=True)
        if res:
            nearest_r = res[0]["price"]
            lines.append(f"Nearest resistance was ${nearest_r:,.1f} — price {'reached it' if (day_range and day_range[0] >= nearest_r) else 'has not reached it yet'}")
        if sup:
            nearest_s = sup[0]["price"]
            lines.append(f"Nearest support was ${nearest_s:,.1f} — price {'tested it' if (day_range and day_range[1] <= nearest_s) else 'has not tested it'}")

    return "\n".join(lines) if lines else "Live price data not available — market may not be open yet."


def _build_scenario_msg(signal_data, smc_data, atr, headlines, web_snippets):
    sig    = signal_data.get("signal", "NO SIGNAL")
    prob   = signal_data.get("prob", 0)
    pred_z = signal_data.get("pred_z", 0)
    bt     = signal_data.get("bull_trend", 0)
    mf     = signal_data.get("macro_fast", 0)
    bb     = signal_data.get("bb_pctb", 0)
    ema200 = signal_data.get("ema200", 1)
    close  = signal_data.get("close", 0)
    w_high = signal_data.get("weekly_high", 0)
    w_low  = signal_data.get("weekly_low", 0)
    date   = signal_data.get("date", datetime.now().strftime("%Y-%m-%d"))

    bt_lbl = "BULL" if bt > 0.02 else "BEAR" if bt < -0.02 else "NEUTRAL"
    mf_lbl = "TIGHT (bearish for gold)" if mf > 0.5 else "EASY (bullish for gold)" if mf < -0.5 else "NEUTRAL"

    res = sorted([l for l in smc_data if l["price"] > close], key=lambda x: x["price"])
    sup = sorted([l for l in smc_data if l["price"] < close], key=lambda x: x["price"], reverse=True)

    sl_dist = round(atr * 1.5, 1)
    tp_dist = round(atr * 2.5, 1)
    if sig == "BUY":
        sl_price = round(close - sl_dist, 1)
        tp_price = round(close + tp_dist, 1)
    elif sig == "SELL":
        sl_price = round(close + sl_dist, 1)
        tp_price = round(close - tp_dist, 1)
    else:
        sl_price = tp_price = 0

    news = ""
    for asset, titles in headlines.items():
        if titles:
            news += f"\n{asset}: " + " | ".join(titles[:3])

    world_view = _read_world_view()
    snips_block = "\n".join(f"- {s}" for s in web_snippets) if web_snippets else "none"

    return f"""DATE: {date}  |  RUN TIME: {datetime.now().strftime('%H:%M')} Morocco
SIGNAL: {sig}  |  PROB: {prob:.4f} ({prob:.1%})  |  PRED-Z: {pred_z:+.4f}
CLOSE: ${close:,.2f}  |  WEEKLY: ${w_low:,.1f}–${w_high:,.1f}

FEATURES
Bull_Trend={bt:+.4f} [{bt_lbl}]
Macro_Fast={mf:+.4f} [{mf_lbl}]
BB_PctB={bb:.4f} {'(overbought — caution on BUY entry)' if bb > 0.85 else '(oversold — caution on SELL entry)' if bb < 0.15 else ''}
EMA200_ratio={ema200:.4f} {'(above EMA200 — structural bull)' if ema200 > 1 else '(below EMA200 — structural bear)'}

ATR (14-day): ${atr:,.2f}
ATR-based SL distance: ${sl_dist:,.1f} (1.5x ATR)
ATR-based TP distance: ${tp_dist:,.1f} (2.5x ATR)
Suggested SL from current close: ${sl_price:,.1f}
Suggested TP from current close: ${tp_price:,.1f}
R:R ratio: 1 : {tp_dist/sl_dist:.2f}

SMC LEVELS ABOVE CURRENT PRICE:
{chr(10).join(f"  ${l['price']:,.1f} {l['type']} {l['dir']} {l.get('zone','')}" for l in res[:6]) or '  none'}

SMC LEVELS BELOW CURRENT PRICE:
{chr(10).join(f"  ${l['price']:,.1f} {l['type']} {l['dir']} {l.get('zone','')}" for l in sup[:6]) or '  none'}

LIVE WEB SEARCH — GOLD NEWS AND PRICE:
{snips_block}

HEADLINES:
{news or 'none'}

LONG-TERM WORLD VIEW:
{world_view or 'not yet built'}

YESTERDAY SIGNAL vs TODAY OPENING — HOW DID IT PLAY OUT:
{_yesterday_review(signal_data, smc_data)}

Now produce the complete trade scenario. First assess how yesterday's signal and levels played out vs today's opening — adjust your conviction and entry accordingly. Use the ATR levels as baseline but adjust entry to nearest SMC level on the signal side. Adjust SL to just beyond the nearest opposing structure. Adjust TP to the next major structural target. If the R:R falls below 1.5 after structural adjustment, flag it.

Return ONLY valid JSON:
{{
  "direction": "BUY or SELL",
  "conviction": "HIGH / MEDIUM / LOW — with one sentence explanation",
  "why_signal_fired": "2-3 sentences on which features drove the signal and why they matter",
  "macro_regime": "1-2 sentences on current monetary environment and its implication for gold",
  "smc_alignment": "2 sentences on whether structure confirms or fights the signal",
  "entry_zone": "specific price level or range, referencing the SMC level",
  "entry_reasoning": "why this is the right entry — what makes this level significant",
  "stop_loss": "specific price level",
  "stop_loss_reasoning": "why this level — what structure is it beyond",
  "take_profit": "specific price level",
  "take_profit_reasoning": "what structural target justifies this level",
  "rr_ratio": "calculated R:R as a string e.g. 1:2.1",
  "if_price_goes_against": "what to do if price moves toward SL — at what level do you exit or reassess",
  "if_price_stalls": "what to do if price moves sideways after entry — time-based or level-based exit",
  "if_price_goes_with": "what to do as price approaches TP — partial close or hold",
  "key_invalidation": "one specific thing that would make this setup invalid before you even enter",
  "current_price_note": "brief note on where price is right now relative to entry zone — is it still valid?"
}}"""


def run_scenario(signal_data, smc_levels, feat_df=None, status_callback=None, force=False):
    date_str = signal_data.get("date", datetime.now().strftime("%Y-%m-%d"))

    if not force:
        cached = _load_scenario_cache(date_str)
        if cached:
            if status_callback:
                status_callback("Loaded scenario from today's cache")
            return cached

    if status_callback:
        status_callback("Fetching live opening price...")
    open_p, live_price, _ = _fetch_live_open()
    if live_price:
        signal_data = dict(signal_data)
        signal_data["live_price"] = live_price

    if status_callback:
        status_callback("Computing ATR...")
    atr = _compute_atr(feat_df)

    if status_callback:
        status_callback("Searching web for live gold price and news...")
    snips  = _ddg_search(f"XAU USD gold price right now {datetime.now().strftime('%B %Y')}")
    snips += _ddg_search(f"gold trade outlook {date_str}")

    if status_callback:
        status_callback("Fetching headlines...")
    headlines = fetch_all_headlines()

    if status_callback:
        status_callback("Calling Qwen3-235B scenario builder...")

    user_msg = _build_scenario_msg(signal_data, smc_levels, atr, headlines, snips)
    messages = [
        {"role": "system", "content": SCENARIO_SYSTEM},
        {"role": "user",   "content": user_msg},
    ]
    raw = _call_qwen(messages, max_tokens=1800)

    try:
        result = json.loads(raw)
    except Exception:
        result = {"error": "JSON parse failed", "raw": raw[:400]}

    if "error" not in result:
        result["_atr"]       = atr
        result["_generated"] = datetime.now().strftime("%H:%M")
        _save_scenario_cache(date_str, result)

    return result


# ─────────────────────────────────────────────
# STREAMLIT RENDER
# ─────────────────────────────────────────────

def render_qwen_section(sig, r, current, w_high, w_low, i_high, i_low, deduped, raw_df, feat_df=None):
    st.markdown('<div class="section-label">QWEN3 MARKET BRIEFING</div>', unsafe_allow_html=True)

    st.markdown("""<style>
    .qwen-card{background:#0c0f14;border:1px solid #1c2030;border-radius:6px;overflow:hidden;margin-bottom:10px;}
    .qwen-card-hdr{padding:9px 14px 7px;border-bottom:1px solid #1c2030;font-family:'JetBrains Mono',monospace;font-size:0.58rem;letter-spacing:0.16em;text-transform:uppercase;}
    .qwen-card-body{padding:11px 14px;font-family:'Space Grotesk',sans-serif;font-size:0.82rem;color:#9ca8b8;line-height:1.8;}
    .scenario-card{background:#060a0f;border:1px solid rgba(245,200,66,0.2);border-radius:6px;overflow:hidden;margin-bottom:10px;}
    .scenario-hdr{padding:9px 14px 7px;border-bottom:1px solid rgba(245,200,66,0.15);font-family:'JetBrains Mono',monospace;font-size:0.58rem;letter-spacing:0.16em;text-transform:uppercase;color:var(--accent);}
    .scenario-body{padding:11px 14px;font-family:'Space Grotesk',sans-serif;font-size:0.82rem;color:#9ca8b8;line-height:1.8;}
    .scenario-level{font-family:'JetBrains Mono',monospace;font-size:0.9rem;font-weight:600;}
    .sc-buy{color:#10d988;} .sc-sell{color:#ff4d6a;} .sc-sl{color:#ff4d6a;} .sc-tp{color:#10d988;}
    .conviction-high{color:#10d988;font-weight:600;} .conviction-med{color:var(--accent);font-weight:600;} .conviction-low{color:#ff4d6a;font-weight:600;}
    .scenario-row{display:flex;justify-content:space-between;align-items:flex-start;padding:6px 0;border-bottom:1px solid #1c2030;gap:16px;}
    .scenario-row:last-child{border-bottom:none;}
    .scenario-k{font-family:'JetBrains Mono',monospace;font-size:0.58rem;color:#3d4a5c;letter-spacing:0.1em;min-width:160px;flex-shrink:0;}
    .scenario-v{font-family:'Space Grotesk',sans-serif;font-size:0.8rem;color:#e2e8f0;flex:1;text-align:left;}
    .cached-badge{font-family:'JetBrains Mono',monospace;font-size:0.52rem;color:#3d4a5c;letter-spacing:0.1em;padding:3px 8px;border:1px solid #1c2030;border-radius:99px;display:inline-block;margin-bottom:8px;}
    div.stButton > button{background:#0c0f14!important;color:#e2e8f0!important;
        border:1px solid #252a38!important;border-radius:2px!important;
        font-family:'JetBrains Mono',monospace!important;font-size:0.72rem!important;
        font-weight:600!important;letter-spacing:0.18em!important;
        text-transform:uppercase!important;box-shadow:none!important;}
    div.stButton > button:hover{background:#111520!important;border-color:#3d4a5c!important;}
    </style>""", unsafe_allow_html=True)

    payload = ({
        "signal": sig, "prob": r.get("prob",0), "pred_z": r.get("pred_z",0),
        "bull_trend": r.get("bull_trend",0), "macro_fast": r.get("macro_fast",0),
        "bb_pctb": r.get("bb_pctb",0), "ema200": r.get("ema200",1),
        "close": current, "weekly_high": w_high, "weekly_low": w_low,
        "intraday_high": i_high, "intraday_low": i_low,
        "date": str(raw_df.index[-1].date()),
    } if r and isinstance(r, dict) else {
        "signal":"NO SIGNAL","prob":0,"pred_z":0,"bull_trend":0,
        "macro_fast":0,"bb_pctb":0,"ema200":1,"close":current,
        "weekly_high":w_high,"weekly_low":w_low,
        "intraday_high":i_high,"intraday_low":i_low,
        "date":str(raw_df.index[-1].date())
    })
    date_str = payload["date"]

    # ── BRIEFING ──────────────────────────────
    briefing_cached = _load_briefing_cache(date_str)
    if briefing_cached:
        st.markdown('<span class="cached-badge">BRIEFING CACHED — TODAY</span>', unsafe_allow_html=True)

    if st.button("RUN QWEN3 BRIEFING", use_container_width=True, key="briefing_btn"):
        status = st.empty()
        def cb(msg):
            status.markdown(f'<div class="candle-status cs-warn">{msg}</div>', unsafe_allow_html=True)
        result, _ = run_briefing(payload, deduped, cb)
        status.empty()
        st.session_state["qwen_result"]  = result
        st.session_state["qwen_payload"] = payload

    if briefing_cached and "qwen_result" not in st.session_state:
        st.session_state["qwen_result"]  = briefing_cached
        st.session_state["qwen_payload"] = payload

    result = st.session_state.get("qwen_result")
    if result and "error" not in result:
        cards = [
            ("GLOBAL MARKET CONTEXT",  result.get("market_context",""),    "var(--accent)"),
            ("FEATURE READING",        result.get("feature_reading",""),   "var(--muted2)"),
            ("SMC STRUCTURE ANALYSIS", result.get("smc_analysis",""),      "var(--muted2)"),
            ("ASSET CONNECTIONS",      result.get("asset_connections",""), "var(--muted2)"),
            ("FORWARD OUTLOOK",        result.get("forward_outlook",""),   "#7F77DD"),
        ]
        for title, body, color in cards:
            if body:
                st.markdown(
                    f'<div class="qwen-card">'
                    f'<div class="qwen-card-hdr" style="color:{color}">{title}</div>'
                    f'<div class="qwen-card-body">{body}</div>'
                    f'</div>', unsafe_allow_html=True)
    elif result and "error" in result:
        st.markdown(f'<div class="candle-status cs-danger">Qwen error: {result["error"]}</div>', unsafe_allow_html=True)

    # ── SCENARIO ──────────────────────────────
    prob = payload.get("prob", 0)
    if prob < TRADE_PROB_MIN and sig not in ("BUY","SELL"):
        st.markdown(f'<div style="font-family:\'JetBrains Mono\',monospace;font-size:0.6rem;color:#3d4a5c;padding:8px 0">TRADE SCENARIO — not available (prob={prob:.1%} &lt; 60% threshold)</div>', unsafe_allow_html=True)
        return

    st.markdown(_section_label("TRADE SCENARIO BUILDER"), unsafe_allow_html=True)

    scenario_cached = _load_scenario_cache(date_str)
    col_btn, col_regen = st.columns([3, 1])
    with col_btn:
        gen_label = "REGENERATE SCENARIO" if scenario_cached else "GENERATE TRADE SCENARIO"
        run_scenario_btn = st.button(gen_label, use_container_width=True, key="scenario_btn")
    with col_regen:
        if scenario_cached:
            st.markdown(f'<div class="cached-badge" style="margin-top:8px">CACHED {scenario_cached.get("_generated","")}</div>', unsafe_allow_html=True)

    if run_scenario_btn:
        status2 = st.empty()
        def cb2(msg):
            status2.markdown(f'<div class="candle-status cs-warn">{msg}</div>', unsafe_allow_html=True)
        scenario = run_scenario(payload, deduped, feat_df=feat_df, status_callback=cb2, force=run_scenario_btn)
        status2.empty()
        st.session_state["scenario_result"] = scenario

    if scenario_cached and "scenario_result" not in st.session_state:
        st.session_state["scenario_result"] = scenario_cached

    scenario = st.session_state.get("scenario_result")
    if not scenario:
        return

    if "error" in scenario:
        st.markdown(f'<div class="candle-status cs-danger">Scenario error: {scenario["error"]}</div>', unsafe_allow_html=True)
        return

    direction  = scenario.get("direction", sig)
    conviction = scenario.get("conviction", "")
    conv_cls   = "conviction-high" if "HIGH" in conviction.upper() else "conviction-med" if "MEDIUM" in conviction.upper() else "conviction-low"
    dir_cls    = "sc-buy" if direction == "BUY" else "sc-sell"
    atr_val    = scenario.get("_atr", "")

    st.markdown(f"""
    <div class="scenario-card">
      <div class="scenario-hdr">
        <span class="scenario-level {dir_cls}">{direction}</span>
        &nbsp;·&nbsp;
        <span class="{conv_cls}">{conviction}</span>
        {f'&nbsp;·&nbsp;<span style="color:#3d4a5c;font-size:0.52rem">ATR=${atr_val}</span>' if atr_val else ''}
      </div>
      <div class="scenario-body">
        <div class="scenario-row"><span class="scenario-k">WHY SIGNAL FIRED</span><span class="scenario-v">{scenario.get('why_signal_fired','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">MACRO REGIME</span><span class="scenario-v">{scenario.get('macro_regime','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">SMC ALIGNMENT</span><span class="scenario-v">{scenario.get('smc_alignment','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">ENTRY ZONE</span><span class="scenario-v scenario-level {dir_cls}">{scenario.get('entry_zone','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">ENTRY REASONING</span><span class="scenario-v">{scenario.get('entry_reasoning','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">STOP LOSS</span><span class="scenario-v scenario-level sc-sl">{scenario.get('stop_loss','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">SL REASONING</span><span class="scenario-v">{scenario.get('stop_loss_reasoning','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">TAKE PROFIT</span><span class="scenario-v scenario-level sc-tp">{scenario.get('take_profit','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">TP REASONING</span><span class="scenario-v">{scenario.get('take_profit_reasoning','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">R:R RATIO</span><span class="scenario-v">{scenario.get('rr_ratio','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">IF PRICE GOES AGAINST</span><span class="scenario-v">{scenario.get('if_price_goes_against','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">IF PRICE STALLS</span><span class="scenario-v">{scenario.get('if_price_stalls','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">IF PRICE GOES WITH YOU</span><span class="scenario-v">{scenario.get('if_price_goes_with','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">INVALIDATION</span><span class="scenario-v">{scenario.get('key_invalidation','')}</span></div>
        <div class="scenario-row"><span class="scenario-k">CURRENT PRICE NOTE</span><span class="scenario-v">{scenario.get('current_price_note','')}</span></div>
      </div>
    </div>""", unsafe_allow_html=True)


def _section_label(text):
    return f'<div class="section-label">{text}</div>'